
server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  #thymeleaf
  thymeleaf:
    cache: false
    prefix:  classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    mode: HTML
  #这个是关键，放开springboot对静态资源的拦截
  mvc:
    static-path-pattern: /static/**

  datasource:
    db0:
      url : jdbc:mysql://localhost:3306/project1?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username : root
      password : qiuhen
      driverClassName : com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

mybatis:

  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qiuhen.interfaces.pojo


logging:
  # 配置输出额日志文件名,可以带路径
  #  file: out.log
  # 配置日志存放路径,日志文件名为：spring.log
  path: ./log                    #path与file同时存在path失效
  file:
    # 设置日志文件大小
    max-size: 10MB
  level:
    # root日志以WARN级别输出
    root: info
    # 此包下所有class以DEBUG级别输出
    com.qiuhen.interfaces.pojo: warn

#pagehelper分页插件配置 以下属性不加也可以实现分页功能
pagehelper:
  helperDialect: mysql
  pareasonable: true
  supportMethodsArguments: true
  params=count: countSql